### ISSUE TITLE
reporte de practica architect

### ISSUE THREAD

**Issue by Arnold-Js** [SistemasTecTlaxiaco/practica-architect-Arnold-Js#1]
[reporte de practica.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Arnold-Js/files/7147240/reporte.de.practica.pdf)
[Diagramas de Clases.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Arnold-Js/files/7147242/Diagramas.de.Clases.pdf)

**Comment by josealfredo79** [comment]
Falta calificacion

**Comment by Yeim1129** [comment]
Calificacion: 17.4
Calificó: J Manuel Hernandez Arroyo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
